apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: inference-health-check
  namespace: mlops
spec:
  args:
    - name: service-name
  metrics:
    - name: p99-latency
      interval: 30s
      count: 4
      failureLimit: 1
      successCondition: result[0] < 0.2
      provider:
        prometheus:
          address: http://prom-kube-prometheus-stack-prometheus.monitoring.svc.cluster.local:9090
          query: |
            histogram_quantile(0.99,
              sum by (le) (
                rate(anomaly_prediction_latency_seconds_bucket{role="champion"}[2m])
              )
            )
    - name: anomaly-flag-rate
      interval: 30s
      count: 4
      failureLimit: 1
      successCondition: result[0] < 0.15
      provider:
        prometheus:
          address: http://prom-kube-prometheus-stack-prometheus.monitoring.svc.cluster.local:9090
          query: |
            sum(rate(anomaly_predictions_total{is_anomaly="1"}[2m]))
            /
            sum(rate(anomaly_predictions_total[2m]))