apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: mlops
resources:
  - mlflow.yaml
  - inference-rollout.yaml
  - analysis-template.yaml
  - podmonitor.yaml
configMapGenerator:
  - name: mlops-config
    namespace: mlops
    literals:
      - prediction_bucket=anomaly-mlops-artifacts-dev
      - artifact_root=s3://anomaly-mlops-artifacts-dev/mlflow
generatorOptions:
  disableNameSuffixHash: true
